print("Varata mame durr")
print("Varata mame durr")
print("Varata mame durr")
print("avan sethaan da ")
print("evanda enaku custody")
print("hello makkale")
print("hello makkale")
print("hello makkale")
print("hello makkale")
print("hello makkale")